"""Maternity and postpartum additions based on the supplied portfolio."""

POSTPARTUM = {
 'title': ('Postpartum & newborn photographer Netherlands | Vicon Creator', 'Kraamreportage & newborn fotografie | Vicon Creator'),
 'description': ('Cinematic postpartum, mother and baby, breastfeeding and lifestyle newborn photography at home across the Netherlands. Plan a gentle session with Viktoriia.', 'Een persoonlijke kraamreportage, moeder-en-babyfoto’s en lifestyle newborn fotografie aan huis in Nederland. Plan een rustige fotoshoot met Viktoriia.'),
 'heading': ('Postpartum.\nYour first chapter\ntogether.', 'De kraamtijd.\nJullie eerste\nhoofdstuk samen.'),
 'intro': ('A baby in your arms. A hand around your finger. Feeding, resting, getting to know each other. Postpartum photography keeps the ordinary closeness of these first weeks and months — at your pace, in a place that feels like you.', 'Een baby in je armen. Een handje om je vinger. Voeden, rusten en elkaar leren kennen. Een kraamreportage bewaart de gewone, bijzondere nabijheid van de eerste weken en maanden. Op jullie tempo, op een plek die bij jullie past.'),
 'gallery': ['motherhood-07','motherhood-01','motherhood-03','motherhood-05','motherhood-02','motherhood-08','motherhood-06','motherhood-09','motherhood-10'],
 'sections': [
  (('Life with your baby, as it feels.', 'Het leven met jullie baby, zoals het voelt.'), ('This is lifestyle newborn and mother-and-baby photography: you holding your baby, a quiet feed, a partner taking a turn, the small details you notice every day. Warm light and expressive black and white connect the images. There is no need for your baby to sleep on cue or for you to look a particular way.', 'Dit is lifestyle newborn fotografie: jullie met de baby, een rustig voedingsmoment, een partner die het even overneemt en de kleine details van elke dag. Warm licht en expressief zwart-wit brengen de beelden samen. Je baby hoeft niet op commando te slapen en jij hoeft er niet op een bepaalde manier uit te zien.')),
  (('At home, with room to pause.', 'Thuis, met ruimte voor een pauze.'), ('A window, a bed or a favourite chair can be enough. Before the session, we can choose one or two spots with available light; your whole home does not need to be tidy. Feeding, changing and settling breaks belong to the session. Share the city and any preferences in your enquiry so we can agree a comfortable time and duration.', 'Een raam, een bed of een fijne stoel kan genoeg zijn. Vooraf kunnen we één of twee plekken met daglicht kiezen; je hele huis hoeft niet opgeruimd te zijn. Pauzes voor voeden, verschonen en troosten horen erbij. Deel jullie woonplaats en wensen in de aanvraag, zodat we een prettig tijdstip en de duur kunnen afspreken.')),
  (('Motherhood, on your terms.', 'Moederschap, op jouw manier.'), ('Breastfeeding photographs, bottle feeding, a postpartum portrait or simply being held: you decide what belongs in your story. Tell me what you would like photographed and what you prefer to keep outside the frame. Partners and siblings can join. We agree image sharing separately; making an enquiry does not give permission to publish your family photographs.', 'Borstvoedingsfoto’s, een flesje geven, een portret na de bevalling of gewoon samen zijn: jullie bepalen wat bij het verhaal hoort. Vertel wat jullie graag willen vastleggen en wat buiten beeld mag blijven. Partners en broertjes of zusjes kunnen meedoen. Delen van foto’s spreken we apart af; een aanvraag is geen toestemming om jullie gezinsfoto’s te publiceren.')),
  (('Across the Netherlands.', 'Door heel Nederland.'), ('I am based in the Netherlands and travel for sessions in Amsterdam, The Hague / Den Haag, Rotterdam, Utrecht and other Dutch towns. Your address, travel costs, image collection and delivery timing are agreed privately before booking.', 'Ik werk vanuit Nederland en kom voor sessies naar Amsterdam, Den Haag, Rotterdam, Utrecht en andere Nederlandse plaatsen. Jullie adres, reiskosten, fotoselectie en levertijd spreken we privé af vóór de boeking.')),
 ],
 'faq': [
  ('When should we plan postpartum or newborn photographs?', 'Choose a time when you feel ready to welcome a photographer. The first weeks can capture a very new chapter; a later session can tell the story of life with a growing baby. You can enquire during pregnancy and discuss a flexible plan. There is no promised age window or requirement for a sleeping baby.', 'Wanneer plannen we een kraamreportage of newbornshoot?', 'Kies een moment waarop jullie eraan toe zijn een fotograaf te ontvangen. De eerste weken laten een heel nieuw hoofdstuk zien; later vertelt de reportage het verhaal van jullie groeiende baby. Je kunt tijdens de zwangerschap alvast informeren en een flexibel plan bespreken. Er is geen vaste leeftijdsgrens of verplichting dat de baby slaapt.'),
  ('Is this a posed newborn studio session?', 'The focus is on natural connection with parents and everyday details. This portfolio does not offer complex newborn poses, props or birth coverage. If you have another idea, choose Other in the enquiry form and describe it so we can discuss whether it fits.', 'Is dit een geposeerde newbornshoot in een studio?', 'De nadruk ligt op natuurlijke nabijheid met ouders en alledaagse details. Dit portfolio biedt geen ingewikkelde newbornposes, decorstukken of geboortereportages aan. Kies bij een ander idee Anders in het formulier, zodat we kunnen bespreken of het past.'),
  ('Can breastfeeding be part of the session?', 'Yes, if you want it to be. Breastfeeding, bottle feeding and moments between feeds can all be photographed. We discuss your boundaries beforehand, and you can change your mind at any time during the session.', 'Kan borstvoeding onderdeel zijn van de fotoshoot?', 'Ja, als je dat graag wilt. Borstvoeding, flesvoeding en momenten tussen voedingen kunnen allemaal in beeld komen. We bespreken vooraf je grenzen; tijdens de sessie kun je die altijd aanpassen.'),
  ('What should we wear and prepare?', 'Choose comfortable clothes you already feel good in. Soft, simple colours keep attention on faces and gestures. Have the baby’s usual feeding and changing things close by. A familiar blanket can be lovely; a new wardrobe or decorated nursery is not necessary.', 'Wat trekken we aan en wat leggen we klaar?', 'Kies comfortabele kleding waarin je je prettig voelt. Rustige, eenvoudige kleuren houden de aandacht bij gezichten en gebaren. Leg de gewone voedings- en verschoonspullen dichtbij. Een vertrouwd dekentje kan mooi zijn; nieuwe kleding of een ingerichte babykamer is niet nodig.'),
  ('How much does a postpartum photoshoot cost?', 'Postpartum sessions receive a personal quote because the duration, location and collection are agreed around your family. The Motherhood price on the investment page is a provisional maternity reference, not a confirmed postpartum package. Ask for a proposal with travel and any other costs clearly included.', 'Wat kost een kraamreportage?', 'Voor een kraamreportage ontvang je een persoonlijk voorstel, omdat duur, locatie en fotocollectie bij jullie gezin moeten passen. De richtprijs voor Motherhood op de tarievenpagina geldt voorlopig voor een zwangerschapsshoot, niet als vast kraampakket. Vraag een voorstel waarin reizen en eventuele andere kosten duidelijk zijn opgenomen.'),
 ]
}

def apply_updates(routes, services, alts):
 routes['postpartum'] = ('/postpartum-newborn-photographer-netherlands/', '/nl/kraamreportage-newborn-fotografie/')
 v = services['maternity']
 v.update({
  'label': ('Motherhood', 'Moederschap'),
  'tag': ('Before & after we meet', 'Voor en na de eerste ontmoeting'),
  'title': ('Maternity & motherhood photographer Netherlands | Vicon Creator', 'Zwangerschap & moederschap fotografie | Vicon Creator'),
  'description': ('Maternity and postpartum photography in the Netherlands. Cinematic pregnancy portraits, mother and baby photographs and quiet moments of early motherhood.', 'Zwangerschapsfotografie en kraamreportages in Nederland. Filmische zwangerschapsportretten, moeder-en-babyfoto’s en de eerste momenten samen.'),
  'heading': ('Motherhood.\nBefore & after\nwe meet.', 'Moederschap.\nVoor & na\nde eerste ontmoeting.'),
  'seoLabel': ('Maternity & postpartum photography · Netherlands', 'Zwangerschapsfotografie & kraamreportages · Nederland'),
  'intro': ('The anticipation of pregnancy. The first days with your baby. A new way of being together. Maternity and postpartum photographs that give space to your body, your closeness and your own pace.', 'Het uitkijken naar je baby. De eerste dagen samen. Een nieuwe manier van dichtbij zijn. Zwangerschapsfoto’s en kraamreportages met ruimte voor je lichaam, jullie nabijheid en jullie eigen tempo.'),
  'gallery': ['motherhood-04','motherhood-07','motherhood-01','motherhood-03','motherhood-05','motherhood-02','motherhood-08','motherhood-06','motherhood-09','motherhood-10'],
  'galleryIntro': ('From a pregnancy in the open air to feeding, holding and getting to know a new baby. Warm colour and black and white, brought together by closeness.', 'Van een zwangerschap in de buitenlucht tot voeden, vasthouden en jullie baby leren kennen. Warme kleuren en zwart-wit, verbonden door nabijheid.'),
  'body': ('For maternity portraits, we choose a setting and movement that feel comfortable: outdoors, at home or in an agreed indoor space. For postpartum photographs, the session follows life with your baby, with room to feed, change and pause. Gentle guidance leaves space for your own connection.', 'Voor zwangerschapsportretten kiezen we een omgeving en beweging die prettig voelen: buiten, thuis of op een afgesproken binnenlocatie. Na de geboorte volgt de sessie het leven met jullie baby, met ruimte om te voeden, verschonen en pauzeren. Rustige begeleiding laat ruimte voor jullie eigen verbinding.'),
  'body2': ('Based in the Netherlands, available for maternity and mother-and-baby sessions across the country. Partners and children are welcome. We discuss your preferences, privacy, location and the full proposal before confirming a date.', 'Vanuit Nederland beschikbaar voor zwangerschaps- en moeder-en-babysessies door het hele land. Partners en kinderen zijn welkom. We bespreken jullie wensen, privacy, locatie en het volledige voorstel voordat we een datum bevestigen.'),
  'includes': (['A personal conversation about your chapter', 'Comfortable movement and gentle guidance', 'Partner or children welcome', 'Cinematic colour and expressive black and white'], ['Een persoonlijk gesprek over jullie hoofdstuk', 'Comfortabele beweging en rustige begeleiding', 'Partner of kinderen welkom', 'Filmische kleur en expressief zwart-wit']),
  'unit': ('Maternity reference · approx. 60 minutes. Postpartum: personal quote.', 'Richtprijs zwangerschap · circa 60 minuten. Kraamreportage: persoonlijk voorstel.'),
 })
 v['faq'].append(('Do you also photograph life after birth?', 'Yes. Postpartum sessions focus on you and your baby, including natural moments at home and feeding if you wish. Visit the postpartum page for the photographs, approach and planning details.', 'Fotografeer je ook de periode na de geboorte?', 'Ja. Kraamreportages richten zich op jullie en de baby, met natuurlijke momenten thuis en eventueel het voeden. Op de kraamreportagepagina vind je de foto’s, aanpak en praktische informatie.'))
 services['events']['gallery'] = ['event-08','event-09','event-10','event-11','event-12','event-13','event-14'] + services['events']['gallery']
 services['events']['wide'] = list(dict.fromkeys([*services['events'].get('wide', []), 'event-09', 'event-12']))
 new_alts = {
  'motherhood-01': ('Baby resting on light fabric in warm sunlight', 'Baby op lichte stof in warm zonlicht'),
  'motherhood-02': ('Mother breastfeeding her baby in warm side light', 'Moeder geeft haar baby borstvoeding in warm zijlicht'),
  'motherhood-03': ('Black-and-white portrait of a father holding his baby', 'Zwart-witportret van een vader met zijn baby'),
  'motherhood-04': ('Expectant parents standing close together in a green field', 'Aanstaande ouders dicht bij elkaar in een groen veld'),
  'motherhood-05': ('Baby holding a parent’s finger, photographed in black and white', 'Baby houdt een vinger van een ouder vast, in zwart-wit'),
  'motherhood-06': ('Black-and-white detail of a baby’s hands and feet on a blanket', 'Zwart-witdetail van babyhandjes en voetjes op een deken'),
  'motherhood-07': ('Mother holding her baby in golden window light', 'Moeder met haar baby in goudkleurig raamlicht'),
  'motherhood-08': ('Mother with a sleeping baby against her shoulder in black and white', 'Moeder met een slapende baby tegen haar schouder in zwart-wit'),
  'motherhood-09': ('Baby looking out while resting against a parent’s shoulder', 'Baby kijkt om zich heen tegen de schouder van een ouder'),
  'motherhood-10': ('Black-and-white portrait of a mother breastfeeding on a bed', 'Zwart-witportret van een moeder die borstvoeding geeft op bed'),
  'event-08': ('Women dancing at a party among swirling light trails', 'Vrouwen dansen op een feest tussen bewegende lichtsporen'),
  'event-09': ('Candid dance-floor moment with colourful light trails', 'Spontaan moment op de dansvloer met gekleurde lichtsporen'),
  'event-10': ('Guest waving a napkin during a lively celebration', 'Gast zwaait met een servet tijdens een levendig feest'),
  'event-11': ('Seated guest holding a drink at an evening gathering', 'Zittende gast met een drankje tijdens een avondbijeenkomst'),
  'event-12': ('Guests mingling in a warmly lit venue with motion blur', 'Gasten ontmoeten elkaar in een warm verlichte zaal met bewegingsonscherpte'),
  'event-13': ('Two party guests surrounded by green light trails', 'Twee feestgasten omringd door groene lichtsporen'),
  'event-14': ('Portrait of a guest wearing a cap in a warmly lit bar', 'Portret van een gast met een pet in een warm verlichte bar'),
 }
 alts.update(new_alts)
