"""Client planning pages: one page per decision, bilingual and without invented shoots."""
EXTRA_ROUTES = {
 'city-amsterdam':('/photographer-amsterdam/','/nl/fotograaf-amsterdam/'),
 'city-hague':('/photographer-the-hague/','/nl/fotograaf-den-haag/'),
 'city-rotterdam':('/photographer-rotterdam/','/nl/fotograaf-rotterdam/'),
 'city-utrecht':('/photographer-utrecht/','/nl/fotograaf-utrecht/'),
 'guides':('/photoshoot-guides/','/nl/fotoshoot-tips/'),
 'guide-wedding':('/photoshoot-guides/wedding-photography-timeline/','/nl/fotoshoot-tips/planning-trouwfotografie/'),
 'guide-outfits':('/photoshoot-guides/what-to-wear/','/nl/fotoshoot-tips/kleding/'),
 'guide-rain':('/photoshoot-guides/rainy-day-photoshoot/','/nl/fotoshoot-tips/regen/'),
 'guide-maternity':('/photoshoot-guides/planning-maternity-photos/','/nl/fotoshoot-tips/zwangerschapsshoot-plannen/'),
 'guide-family':('/photoshoot-guides/family-session-with-children/','/nl/fotoshoot-tips/gezinsshoot-met-kinderen/'),
 'guide-events':('/photoshoot-guides/event-photography-brief/','/nl/fotoshoot-tips/briefing-evenementenfotografie/'),
}
# Each tuple is English, Dutch. Local facts have tourism-board sources;
# creative and scheduling suggestions are editorial planning advice, not claims of visits.
CITIES = {
 'city-amsterdam': {
  'name':('Amsterdam','Amsterdam'),'hero':'lovestory-07',
  'title':('Photographer Amsterdam | Couples, portraits & family','Fotograaf Amsterdam | Loveshoot, portret & gezin'),
  'intro':('A photoshoot in Amsterdam can be a quiet walk together, a personal portrait or time with your family. Vicon Creator works on location, with cinematic colour and expressive black-and-white photography. Start with the kind of day you want to have, then choose the backdrop.','Een fotoshoot in Amsterdam kan een rustige wandeling samen zijn, een persoonlijk portret of tijd met je gezin. Vicon Creator werkt op locatie, met filmische kleuren en expressief zwart-wit. Begin bij hoe je de dag wilt beleven en kies daarna de achtergrond.'),
  'sections':[
   (('Canals or a more personal setting?','Grachten of een plek met betekenis?'),('The Jordaan combines canal streets, bridges and a residential feel. A short route there can suit couples and individual portraits, but a landmark does not have to be the goal. A street you know or a place connected to your relationship may tell more of your story. Choose one neighbourhood instead of trying to fit the whole city into a session.','De Jordaan combineert grachtenstraten, bruggen en een buurtgevoel. Een korte route kan passen bij koppels en portretten, maar een herkenbaar monument hoeft niet het doel te zijn. Een vertrouwde straat of een plek uit jullie verhaal kan meer betekenis hebben. Kies één buurt in plaats van de hele stad in een sessie te willen stoppen.')),
   (('Plan the route around people','Plan de route rond de mensen'),('Tell me whether you are visiting Amsterdam or live here, how many people will join and how much walking feels comfortable. For children, plan room for a pause and keep the route away from a tight sightseeing schedule. Agree the meeting point and a finish near your next stop. Crowds and access can change, so the exact route is confirmed for your date.','Vertel of je Amsterdam bezoekt of hier woont, hoeveel mensen meegaan en hoeveel wandelen prettig is. Houd met kinderen ruimte voor een pauze en zet de shoot niet tussen twee strak geplande uitstapjes. Spreek een ontmoetingspunt en een handig eindpunt af. Drukte en toegankelijkheid kunnen veranderen; de precieze route stemmen we af op de datum.')),
   (('Portraits, families and celebrations','Portretten, gezinnen en vieringen'),('For portraits, share how you will use the images and whether you prefer the city to be recognisable or softly in the background. For a family session, share the ages of the children. For an event, send the venue and programme. Wedding plans have their own Amsterdam page, with coverage and travel considerations.','Vertel bij portretten waarvoor je de beelden wilt gebruiken en of de stad herkenbaar of juist zacht op de achtergrond mag zijn. Geef bij een gezinsshoot de leeftijden van de kinderen door. Stuur voor een evenement de locatie en het programma. Voor trouwplannen is er een aparte Amsterdam-pagina met informatie over reportage en reis.')),
  ],'links':['couples','portraits','family','amsterdam'],'source':('I amsterdam: Jordaan','https://www.iamsterdam.com/en/explore/neighbourhoods/centrum/things-to-do-in-the-jordaan')},
 'city-hague': {
  'name':('The Hague / Den Haag','Den Haag'),'hero':'lovestory-18',
  'title':('Photographer The Hague | Maternity, couples & portraits','Fotograaf Den Haag | Zwangerschap, loveshoot & portret'),
  'intro':('In The Hague, the first choice is often between a city setting and the coast. For a love story, maternity portrait or family photoshoot, that choice changes the walking, clothing and pace. Vicon Creator offers sessions in Den Haag by arrangement, with the same cinematic approach throughout.','In Den Haag begint de keuze vaak bij de stad of de kust. Bij een loveshoot, zwangerschapsportret of gezinsshoot heeft dat invloed op het wandelen, de kleding en het tempo. Vicon Creator biedt fotoshoots in Den Haag in overleg, met dezelfde filmische benadering.'),
  'sections':[
   (('Beach, dunes or city','Strand, duinen of stad'),('Scheveningen and Kijkduin offer a coastal setting; the dune landscapes around The Hague give a different texture from city streets. Sand and wind become part of the photographs. A city route may suit you better if you prefer firmer paths, layered architecture or less exposure. Location access and any permissions are checked before confirming a plan.','Scheveningen en Kijkduin bieden een kustdecor; de duinlandschappen rond Den Haag hebben een andere textuur dan de stad. Zand en wind worden onderdeel van de beelden. Een stadsroute kan beter passen als je liever over stevige paden loopt, architectuur zoekt of minder in de wind wilt staan. Toegang en eventuele toestemming worden vooraf gecontroleerd.')),
   (('Comfort for maternity and family sessions','Comfort bij zwangerschap en gezin'),('Choose the amount of walking before choosing the view. Tell me if you would like a short route, sitting breaks or somewhere close to the meeting point. For maternity portraits, decide whether you want to be photographed alone or with a partner. For children, clothing that works in the actual weather is more useful than an outfit chosen only for its colour.','Kies eerst hoeveel je wilt wandelen en daarna het uitzicht. Geef aan of je een korte route, zitpauzes of een plek dicht bij het ontmoetingspunt wilt. Bepaal bij zwangerschapsportretten of je alleen of met je partner op de foto wilt. Voor kinderen is kleding die bij het echte weer past nuttiger dan een outfit die alleen op kleur is gekozen.')),
   (('Light and a weather alternative','Licht en een alternatief bij ander weer'),('Warm evening light is one possible mood, not a booking guarantee. Cloud, wind and the season may suggest a different time or backdrop. Agree a sheltered alternative and when a decision will be made. Indoor hire, travel and any change of date need to be discussed in the proposal.','Warm avondlicht is een mogelijke sfeer, geen garantie bij het boeken. Bewolking, wind en het seizoen kunnen aanleiding zijn voor een ander tijdstip of decor. Spreek een beschut alternatief af en wanneer een beslissing wordt genomen. Binnenruimte, reis en een eventuele nieuwe datum worden in het voorstel besproken.')),
  ],'links':['the-hague','maternity','family','portraits'],'source':('Den Haag: dunes','https://denhaag.com/en/do/nature/dunes/locations')},
 'city-rotterdam': {
  'name':('Rotterdam','Rotterdam'),'hero':'portrait-20',
  'title':('Photographer Rotterdam | Portraits & event photography','Fotograaf Rotterdam | Portretten & evenementen'),
  'intro':('Rotterdam offers a strong visual starting point for an expressive portrait or a city love story. For events, the programme and the people set the direction. Vicon Creator works on location in Rotterdam; a portrait session and an event brief each receive a different plan.','Rotterdam biedt een krachtig vertrekpunt voor een expressief portret of een loveshoot in de stad. Bij evenementen bepalen het programma en de mensen de richting. Vicon Creator werkt op locatie in Rotterdam; een portretsessie en een evenement krijgen elk een eigen plan.'),
  'sections':[
   (('Architecture as part of a portrait','Architectuur als onderdeel van een portret'),('Kop van Zuid combines waterfront views with contemporary architecture. Lines, scale and reflections can support a graphic portrait, while a tighter frame can keep the emphasis on expression. Decide whether you want a recognisable Rotterdam backdrop or a more abstract image before planning several locations.','Kop van Zuid combineert water met moderne architectuur. Lijnen, schaal en reflecties kunnen een grafisch portret ondersteunen; een krapper kader legt de nadruk op expressie. Bepaal eerst of Rotterdam herkenbaar moet zijn of dat je een abstracter beeld wilt, voordat je verschillende locaties plant.')),
   (('A useful brief for an event','Een bruikbare briefing voor een evenement'),('For a celebration, launch or company gathering, send the venue, start and finish times, expected guest count and the moments that cannot be repeated. Explain where the photographs will appear: internal communication, a website, social media or a campaign. If several rooms need simultaneous coverage, raise that before requesting a quote.','Stuur voor een feest, lancering of zakelijke bijeenkomst de locatie, begin- en eindtijd, het verwachte aantal gasten en de momenten die niet herhaald kunnen worden. Vertel waar de beelden komen: interne communicatie, website, sociale media of een campagne. Bespreek gelijktijdige programma’s in verschillende zalen voordat je een offerte aanvraagt.')),
   (('Agree access before the session','Stem de toegang vooraf af'),('For a private venue, confirm photography access with the organiser and identify an on-site contact. For portraits outside, agree one practical meeting place and a short route. Travel, venue or studio hire, delivery deadlines and image use belong in the written proposal rather than being assumed from the headline price.','Stem bij een besloten locatie de toegang af met de organisator en wijs een contactpersoon ter plaatse aan. Spreek voor buitenportretten één praktisch ontmoetingspunt en een korte route af. Reis, locatie- of studiohuur, levertermijn en beeldgebruik horen in het schriftelijke voorstel; ga er niet van uit dat alles in de richtprijs zit.')),
  ],'links':['portraits','events','couples','prices'],'source':('Rotterdam: Kop van Zuid','https://www.rotterdam.info/en/visit/guide/visit-kop-van-zuid')},
 'city-utrecht': {
  'name':('Utrecht','Utrecht'),'hero':'kids-02',
  'title':('Photographer Utrecht | Family, couples & portraits','Fotograaf Utrecht | Gezin, loveshoot & portretten'),
  'intro':('A family photoshoot in Utrecht works best when the route fits the family. A couple session or personal portrait may use the same city in a very different way. Vicon Creator photographs on location across the Netherlands, including Utrecht, with the setting chosen around your story.','Een gezinsshoot in Utrecht begint bij een route die bij het gezin past. Een loveshoot of persoonlijk portret kan dezelfde stad heel anders gebruiken. Vicon Creator fotografeert op locatie door heel Nederland, waaronder Utrecht, met een omgeving die past bij jullie verhaal.'),
  'sections':[
   (('Canal level or street level?','Aan de werf of op straatniveau?'),('Utrecht’s canals and wharves offer more than one perspective. Near the Oudegracht, decide whether a waterside setting is practical for everyone or whether staying at street level makes the session easier. A short route with time to stop can be more useful than a checklist of landmarks. Access, steps and current conditions should be checked for your chosen meeting point.','De Utrechtse grachten en werven bieden verschillende perspectieven. Bepaal bij de Oudegracht of een plek aan het water praktisch is voor iedereen, of dat straatniveau prettiger is. Een korte route met tijd om stil te staan kan waardevoller zijn dan een lijst bezienswaardigheden. Controleer toegang, trappen en actuele omstandigheden bij het gekozen ontmoetingspunt.')),
   (('Let children set part of the pace','Laat kinderen een deel van het tempo bepalen'),('For a family session, share the children’s ages, how far you want to walk and whether anyone needs a break or easy access. Bring a familiar layer and a small, easy snack. A session does not have to depend on everyone looking at the camera at once: walking, closeness and individual portraits can also tell the story.','Deel voor een gezinsshoot de leeftijden van de kinderen, hoeveel jullie willen wandelen en of iemand pauzes of makkelijke toegang nodig heeft. Neem een vertrouwd vest en een kleine, handige snack mee. Niet iedereen hoeft tegelijk in de camera te kijken: wandelen, nabijheid en losse portretten vertellen ook jullie verhaal.')),
   (('Couples, portraits and wedding plans','Koppels, portretten en trouwplannen'),('For couples, choose an activity or place that makes conversation easy. For portraits, share the intended use and a few examples of the mood you like. If you are planning a wedding in Utrecht, send the venue and timeline so coverage can be discussed using the Netherlands wedding collection. Travel and any venue costs are agreed before booking.','Kies voor een loveshoot een plek of bezigheid waarbij jullie makkelijk praten. Deel voor portretten het beoogde gebruik en enkele voorbeelden van de gewenste sfeer. Stuur bij een bruiloft in Utrecht de locatie en planning; we bespreken de reportage vanuit de trouwcollectie voor Nederland. Reis en eventuele locatiekosten spreken we vooraf af.')),
  ],'links':['family','couples','portraits','weddings'],'source':('Discover Utrecht: canals and wharves','https://www.discover-utrecht.com/route/35198/canals-and-wharf-cellars-walk')},
}

GUIDES = {
 'guide-wedding':{
  'title':('How many hours of wedding photography do you need?','Hoeveel uur trouwfotografie heb je nodig?'),
  'hero':'wedding-12','services':['weddings'],'related':['guide-rain','prices'],
  'intro':('Work backwards from the moments you want to keep. A six-hour collection and a ten-hour collection do not tell exactly the same part of a wedding day. The right choice depends on your timetable, travel and priorities.','Werk terug vanaf de momenten die jullie willen bewaren. Een collectie van zes uur vertelt niet precies hetzelfde deel van de trouwdag als tien uur. De passende keuze hangt af van planning, reistijd en prioriteiten.'),
  'sections':[
   (('Start with the fixed moments','Begin bij de vaste momenten'),('Write down the ceremony, dinner and party times first. Add the addresses and realistic transfers between them. Then mark which preparations, portraits and family combinations matter most. A photographer cannot be in two places at once, so overlapping plans need to be discussed early.','Schrijf eerst de tijden van ceremonie, diner en feest op. Voeg adressen en realistische reistijd toe. Markeer daarna welke voorbereidingen, portretten en familiecombinaties belangrijk zijn. Een fotograaf kan niet op twee plekken tegelijk zijn; bespreek overlap daarom vroeg.')),
   (('Compare six, eight and ten hours','Vergelijk zes, acht en tien uur'),('Six hours may focus on the ceremony, portraits and reception. Eight can give more room for preparations or dinner, depending on the schedule. Ten can cover a broader part of the day, including some evening atmosphere. These are planning examples, not guaranteed inclusions: a late party or long transfer can change what fits.','Zes uur kan gericht zijn op ceremonie, portretten en receptie. Acht uur kan meer ruimte bieden voor voorbereidingen of diner, afhankelijk van de planning. Tien uur kan een groter deel van de dag omvatten, inclusief avondsfeer. Dit zijn planningsvoorbeelden, geen gegarandeerde onderdelen: een laat feest of lange verplaatsing verandert wat haalbaar is.')),
   (('Protect time together','Bewaar tijd voor jullie samen'),('Instead of one long portrait break, consider whether two short opportunities fit naturally between events. Keep family groups to a written list and nominate someone who knows the guests. Add a buffer around travel and dressing. A relaxed schedule leaves more room for the small moments that make the photographs personal.','Bekijk of twee korte portretmomenten natuurlijk tussen de onderdelen passen, in plaats van één lange onderbreking. Maak een lijst voor familiefoto’s en vraag iemand die de gasten kent om te helpen. Houd ruimte rond reizen en aankleden. Een ontspannen planning laat meer plek voor de kleine momenten die foto’s persoonlijk maken.')),
   (('Send this with your enquiry','Stuur dit mee met je aanvraag'),('Share your date, venue addresses, the earliest and latest moments you want photographed, and your three priorities. Ask for coverage, delivery, image use, travel and the total price in one proposal. The Vicon Creator prices page gives indicative six-, eight- and ten-hour collections; your actual day determines the final scope.','Deel de datum, locatieadressen, het vroegste en laatste moment dat jullie willen laten vastleggen en jullie drie prioriteiten. Vraag om reportage, levering, beeldgebruik, reis en totaalprijs in één voorstel. De tarievenpagina van Vicon Creator geeft richtprijzen voor zes, acht en tien uur; jullie echte dag bepaalt de inhoud.')),
  ]},
 'guide-outfits':{
  'title':('What to wear for a couples, portrait or family photoshoot','Kleding voor een loveshoot, portret of gezinsshoot'),
  'hero':'lovestory-05','services':['couples','portraits','family'],'related':['guide-rain','guide-maternity'],
  'intro':('Choose clothes you can move, sit and breathe comfortably in. The most useful outfit is one that feels like you and works with the location. A cinematic photograph does not require a special wardrobe.','Kies kleding waarin je prettig kunt bewegen, zitten en ademen. De beste outfit voelt als jezelf en past bij de locatie. Voor een filmische foto is geen bijzondere garderobe nodig.'),
  'sections':[
   (('Choose the setting before the palette','Kies de plek vóór de kleuren'),('For a warm outdoor portrait, cream, brown and muted colours can echo the landscape. In a city portrait, a darker jacket or a clear silhouette can support a stronger graphic mood. These are options, not rules. Bring a colour you love if it matters to you; the surroundings and framing can be considered around it.','Bij een warm buitenportret kunnen crème, bruin en gedempte kleuren aansluiten bij het landschap. In de stad kan een donkere jas of duidelijk silhouet een grafische sfeer ondersteunen. Het zijn mogelijkheden, geen regels. Draag gerust een kleur waar je van houdt; omgeving en kader kunnen daarop worden afgestemd.')),
   (('Coordinate without a uniform','Stem af zonder uniform'),('For couples or families, lay the outfits together and check whether one item dominates. Different shades, textures and layers often feel more natural than identical clothing. A large logo or very busy print may draw attention; keep it if it belongs to your story, or choose a quieter alternative when faces should lead.','Leg bij koppels en gezinnen de outfits bij elkaar en kijk of één kledingstuk alles overheerst. Verschillende tinten, stoffen en laagjes voelen vaak natuurlijker dan identieke kleding. Een groot logo of drukke print kan aandacht trekken. Behoud het als het bij jullie verhaal hoort, of kies rustiger als gezichten centraal moeten staan.')),
   (('Test movement and the real weather','Test beweging en het echte weer'),('Try sitting, walking and raising your arms before the session. For children, let comfort decide. Bring a layer you are happy to see in the photographs, plus shoes suited to the route. If you want a second outfit, discuss changing space and time in advance rather than assuming they are included.','Probeer vóór de shoot te zitten, lopen en je armen op te tillen. Laat bij kinderen comfort de doorslag geven. Neem een extra laag mee die ook op de foto mag, met schoenen die bij de route passen. Bespreek bij een tweede outfit vooraf omkleedruimte en tijd; ga er niet van uit dat die inbegrepen zijn.')),
   (('A simple bag checklist','Een eenvoudige paklijst'),('Pack your chosen outfit, a useful extra layer, comfortable walking shoes and any small personal item you want included. Keep pockets light for portraits. Send a quick picture of the outfits with your location idea if you would like to discuss how the colours may work together.','Neem de gekozen outfit, een handige extra laag, comfortabele schoenen en eventueel een klein persoonlijk voorwerp mee. Houd zakken bij portretten zo leeg mogelijk. Stuur een snelle foto van de kleding samen met je locatie-idee als je de combinatie van kleuren wilt bespreken.')),
  ]},
 'guide-rain':{
  'title':('What if it rains on your photoshoot day?','Wat als het regent op de dag van je fotoshoot?'),
  'hero':'lovestory-08','services':['couples','family','weddings'],'related':['guide-outfits','guide-wedding'],
  'intro':('Make a weather plan before the day arrives. Cloud, a light shower and persistent rain call for different decisions. The aim is a session you can enjoy, with the final location and any changes agreed together.','Maak vóór de shoot een plan voor het weer. Bewolking, een korte bui en aanhoudende regen vragen om verschillende keuzes. Het doel is een sessie waarvan je kunt genieten, met afspraken over locatie en eventuele wijzigingen.'),
  'sections':[
   (('Cloud does not mean the session is lost','Bewolking hoeft geen probleem te zijn'),('An overcast sky can give a softer look than direct sun. If your main priority is a relaxed portrait, the session may still suit that mood. If you specifically want the warm backlight shown in parts of this portfolio, discuss that preference when booking; weather-dependent light cannot be promised.','Een bewolkte lucht kan zachter licht geven dan directe zon. Als een ontspannen portret het doel is, kan de shoot nog steeds bij die sfeer passen. Wil je juist het warme tegenlicht uit delen van dit portfolio, bespreek die voorkeur bij het boeken. Licht dat van het weer afhangt kan niet worden beloofd.')),
   (('Choose an alternative that is actually available','Kies een alternatief dat echt beschikbaar is'),('A sheltered street is different from a booked indoor venue. Before relying on a café, hotel or studio, confirm permission, opening times and any hire charge. For a wedding, ask the venue which indoor spaces can be used for portraits if the outdoor plan changes. Do not assume every covered location is available for photography.','Een beschutte straat is iets anders dan een geboekte binnenlocatie. Controleer toestemming, openingstijden en eventuele huur voordat je rekent op een café, hotel of studio. Vraag bij een bruiloft welke binnenruimtes beschikbaar zijn voor portretten. Ga er niet van uit dat elke overdekte plek voor fotografie gebruikt mag worden.')),
   (('Agree who decides and when','Spreek af wie wanneer beslist'),('Put three things in the plan: when you will check in, which alternative is acceptable and what happens if a new date is needed. Discuss wind, temperature, walking conditions and the people joining, not only rainfall. A change of time or date is subject to availability and the terms agreed for your booking.','Leg drie dingen vast: wanneer jullie overleggen, welk alternatief passend is en wat er gebeurt als een nieuwe datum nodig is. Bespreek ook wind, temperatuur, looproute en wie meegaat, niet alleen de regen. Een ander tijdstip of nieuwe datum hangt af van beschikbaarheid en de afgesproken voorwaarden.')),
   (('Bring a practical extra layer','Neem een praktische extra laag mee'),('Choose outerwear and shoes you can comfortably wear between photographs. For children, bring something dry if conditions might be wet. Keep the plan short enough to change direction without rushing. If a particular look matters more than the date, say so in your enquiry.','Kies een jas en schoenen die je prettig tussen de foto’s door kunt dragen. Neem voor kinderen iets droogs mee als het nat kan worden. Houd de route kort genoeg om zonder haast aan te passen. Is een bepaalde sfeer belangrijker dan de datum, vermeld dat dan in de aanvraag.')),
  ]},
 'guide-maternity':{
  'title':('Planning maternity photos: timing, comfort and location','Zwangerschapsshoot plannen: moment, comfort en locatie'),
  'hero':'portrait-01','services':['maternity'],'related':['guide-outfits','guide-rain'],
  'intro':('Begin with how you want to remember this chapter: a quiet portrait on your own, a photograph with your partner, or an outdoor session with warm light. Then discuss a date and a setting that feel comfortable for you.','Begin bij hoe je deze periode wilt bewaren: een rustig portret alleen, een foto met je partner of een buitenshoot met warm licht. Bespreek daarna een datum en omgeving die voor jou prettig voelen.'),
  'sections':[
   (('When should you book a maternity photoshoot?','Wanneer plan je een zwangerschapsshoot?'),('There is no single week that suits everyone. Contact the photographer while there is room to discuss options, and share the period you have in mind. Choose a time when the photographs fit the memory you want and the session feels manageable. You do not need to share private medical details to request a shorter route or more pauses.','Er is niet één week die voor iedereen past. Neem contact op wanneer er nog ruimte is om mogelijkheden te bespreken en geef de gewenste periode door. Kies een moment dat past bij de herinnering die je wilt bewaren en een sessie die haalbaar voelt. Je hoeft geen medische details te delen om een kortere route of extra pauzes te vragen.')),
   (('An outdoor portrait or an indoor setting?','Een buitenportret of een binnenlocatie?'),('The portfolio includes a warm outdoor maternity portrait with flowers. Use it as a starting point for colour and atmosphere, rather than an exact image to reproduce. If you prefer an indoor setting, discuss availability, privacy, light and any location cost before booking. An easy meeting point can matter more than a dramatic view.','Het portfolio bevat een warm zwangerschapsportret buiten met bloemen. Gebruik dat als vertrekpunt voor kleur en sfeer, niet als beeld dat exact moet worden nagemaakt. Bespreek bij een binnenlocatie vooraf beschikbaarheid, privacy, licht en eventuele kosten. Een makkelijk ontmoetingspunt kan belangrijker zijn dan een indrukwekkend uitzicht.')),
   (('Who joins, and what do you wear?','Wie gaat mee en wat trek je aan?'),('Decide whether your partner or children will join for all or part of the session. Choose an outfit that feels like you and lets you move comfortably; there is no requirement to show bare skin. Agree any outfit changes and the type of guidance you would like. A personal item or flowers are optional, not necessary props.','Bepaal of je partner of kinderen de hele sessie of een gedeelte meegaan. Kies kleding die bij je past en waarin je prettig beweegt; blote huid is geen vereiste. Stem omkleden en de gewenste begeleiding af. Een persoonlijk voorwerp of bloemen zijn optioneel, geen verplichte attributen.')),
   (('What to put in the enquiry','Wat zet je in de aanvraag?'),('Send your preferred period, city, who will join, the atmosphere you like and any practical access or walking preference. Ask for the total cost, the edited selection and delivery arrangements in writing. Discuss publication preferences separately from the photographs you receive for yourself.','Stuur de gewenste periode, stad, wie meegaat, de sfeer die je mooi vindt en praktische wensen rond toegang of wandelen. Vraag schriftelijk naar totaalprijs, bewerkte selectie en levering. Bespreek eventuele publicatie apart van de foto’s die je voor jezelf ontvangt.')),
  ]},
 'guide-family':{
  'title':('A family photoshoot with children: a practical plan','Een gezinsshoot met kinderen: praktisch voorbereiden'),
  'hero':'kids-02','services':['family'],'related':['guide-outfits','guide-rain'],
  'intro':('A useful family session plan leaves room for children to be themselves. Start with who is joining, a manageable location and a few photographs that matter to you. The day does not have to depend on a perfect group pose.','Een goed plan voor een gezinsshoot laat kinderen zichzelf zijn. Begin bij wie meegaat, een haalbare locatie en een paar beelden die belangrijk zijn. De sessie hoeft niet af te hangen van één perfecte groepspose.'),
  'sections':[
   (('Keep the route manageable','Houd de route haalbaar'),('Tell the photographer the children’s ages, how many adults will join and whether the group needs easy access. Choose one setting with room to pause instead of moving between several distant spots. A familiar place can make it easier to begin. For a larger family group, list the combinations you would like before the session.','Geef de leeftijden van de kinderen, het aantal volwassenen en eventuele wensen rond toegankelijkheid door. Kies één omgeving met ruimte voor een pauze, in plaats van verschillende verre plekken. Een vertrouwde locatie kan helpen om rustig te beginnen. Maak voor een grotere familie vooraf een lijst met gewenste combinaties.')),
   (('Use the family’s rhythm','Volg het ritme van het gezin'),('Consider the time of day that normally works for your children, and discuss it alongside the light. Avoid arriving hungry or with an immediate appointment afterwards. Bring water, a small snack and a familiar layer. If a child needs time to watch before joining, build that possibility into the plan.','Denk aan het tijdstip dat normaal goed werkt voor de kinderen en bespreek dat naast het licht. Kom liever niet hongerig aan en plan direct daarna geen strakke afspraak. Neem water, een kleine snack en een vertrouwde extra laag mee. Houd er rekening mee dat een kind misschien eerst even wil kijken.')),
   (('Choose moments as well as group photographs','Kies momenten én groepsfoto’s'),('A walk holding hands, a conversation with a parent or a quiet individual portrait can sit alongside the photograph of everyone together. Pick a few priorities, then leave room for the unplanned. You do not need to promise a reward for every smile or rehearse poses in advance.','Hand in hand wandelen, een gesprek met een ouder of een rustig los portret kunnen naast de foto van iedereen samen bestaan. Kies enkele prioriteiten en laat ruimte voor het onverwachte. Je hoeft niet voor elke glimlach een beloning te beloven of vooraf poses te oefenen.')),
   (('Agree delivery and sharing','Spreek levering en delen af'),('Ask what edited photographs you will receive, how they will be delivered and when to expect them. Mention any intended prints or gifts so the format can be considered. Discuss whether any images may be used publicly; a family’s preferences should be clear before publication is considered.','Vraag welke bewerkte foto’s je ontvangt, hoe ze worden geleverd en wanneer je ze kunt verwachten. Vermeld eventuele afdrukken of cadeaus, zodat het formaat kan worden meegenomen. Bespreek of beelden openbaar gebruikt mogen worden; de voorkeuren van het gezin moeten duidelijk zijn voordat publicatie wordt overwogen.')),
  ]},
 'guide-events':{
  'title':('What to include in an event photography brief','Wat zet je in een briefing voor evenementenfotografie?'),
  'hero':'event-02','services':['events'],'related':['portraits','prices'],
  'intro':('A clear brief helps an event photographer understand what the images need to do after the event. Start with the audience and intended use, then identify the moments, people and deadlines that matter.','Een heldere briefing maakt duidelijk wat de foto’s na het evenement moeten doen. Begin bij doelgroep en gebruik, en benoem daarna de momenten, mensen en deadlines die belangrijk zijn.'),
  'sections':[
   (('Programme and must-have moments','Programma en onmisbare momenten'),('Send the date, venue address, start and finish times and a programme with the key moments marked. Identify speakers, hosts or guests who need to appear. Flag parallel sessions and restricted areas. A short priority list is more useful than an undifferentiated request to photograph everything.','Stuur datum, locatieadres, begin- en eindtijd en een programma met gemarkeerde hoofdmomenten. Benoem sprekers, organisatoren of gasten die in beeld moeten komen. Meld parallelle programma’s en afgesloten ruimtes. Een korte prioriteitenlijst werkt beter dan een ongerichte vraag om alles vast te leggen.')),
   (('Where will the photographs be used?','Waar worden de foto’s gebruikt?'),('Explain whether the images are for internal reporting, social media, a website, press or paid advertising. Mention horizontal banners, vertical posts or space for text if those formats matter. Usage and any commercial licence should be agreed with the photographer before coverage starts.','Vertel of de beelden voor interne verslaglegging, sociale media, een website, pers of betaalde advertenties zijn. Noem liggende banners, staande posts of ruimte voor tekst als die formaten belangrijk zijn. Gebruik en eventuele commerciële licentie worden vóór de reportage afgesproken.')),
   (('Access, contact and guest preferences','Toegang, contact en voorkeuren van gasten'),('Nominate one person who can help on site. Share access instructions and relevant venue photography restrictions. Tell the photographer how the organiser communicates photography to attendees and identifies anyone who should not be photographed. Agree where any requested portraits can happen without disrupting the programme.','Wijs één contactpersoon ter plaatse aan. Deel toegangsinstructies en relevante fotoregels van de locatie. Vertel hoe de organisator fotografie communiceert aan bezoekers en aangeeft wie niet gefotografeerd wil worden. Spreek af waar eventuele portretten kunnen worden gemaakt zonder het programma te verstoren.')),
   (('Delivery and a comparable quote','Levering en een vergelijkbare offerte'),('State the deadline for any first selection and for the complete delivery. Do not assume same-day photographs are included. Request a proposal covering hours, travel, edited selection, delivery method, image use and total cost. The current Vicon Creator event price is an indicative starting point, with the final brief determining the offer.','Geef de deadline voor een eventuele eerste selectie en de volledige levering. Ga er niet van uit dat beelden dezelfde dag inbegrepen zijn. Vraag een voorstel met uren, reis, bewerkte selectie, levering, beeldgebruik en totaalprijs. Het huidige evenemententarief van Vicon Creator is een richtprijs; de definitieve briefing bepaalt het aanbod.')),
  ]},
}
